<a href="https://colab.research.google.com/github/RRakshit/AIPND/blob/master/basic_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

In [3]:
x=torch.rand(3,2)
x

tensor([[0.9006, 0.1369],
        [0.2934, 0.5816],
        [0.4537, 0.5597]])

In [5]:
y=torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
z =x + y
z

tensor([[1.9006, 1.1369],
        [1.2934, 1.5816],
        [1.4537, 1.5597]])

In [7]:
z[0]

tensor([1.9006, 1.1369])

In [8]:
z[:,:1]

tensor([[1.9006],
        [1.2934],
        [1.4537]])

In [10]:
z.add(1)

tensor([[2.9006, 2.1369],
        [2.2934, 2.5816],
        [2.4537, 2.5597]])

In [11]:
z.size()

torch.Size([3, 2])

In [13]:
z.resize_(2,3)

tensor([[1.9006, 1.1369, 1.2934],
        [1.5816, 1.4537, 1.5597]])

In [15]:
a=np.random.rand(4,3)
a

array([[0.10662577, 0.03915177, 0.91086806],
       [0.1523193 , 0.94133693, 0.28487039],
       [0.02856165, 0.82998353, 0.27429452],
       [0.75703382, 0.53384572, 0.03230303]])

In [16]:
b=torch.from_numpy(a)
b

tensor([[0.1066, 0.0392, 0.9109],
        [0.1523, 0.9413, 0.2849],
        [0.0286, 0.8300, 0.2743],
        [0.7570, 0.5338, 0.0323]], dtype=torch.float64)

In [17]:
b.numpy()

array([[0.10662577, 0.03915177, 0.91086806],
       [0.1523193 , 0.94133693, 0.28487039],
       [0.02856165, 0.82998353, 0.27429452],
       [0.75703382, 0.53384572, 0.03230303]])

In [18]:
b.mul(2)

tensor([[0.2133, 0.0783, 1.8217],
        [0.3046, 1.8827, 0.5697],
        [0.0571, 1.6600, 0.5486],
        [1.5141, 1.0677, 0.0646]], dtype=torch.float64)